name: End-to-end tests

on:
  push:
    branches:
      - master  # ou qualquer outra branch em que você queira rodar os testes

jobs:
  cypress-run:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # ou a versão do Node.js que você está usando

      - name: Install dependencies
        run: |
          npm install

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          start: true  # Inicia os testes do Cypress

      - name: Upload Cypress screenshots
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore  # Se não encontrar arquivos, ignora

      - name: Upload Cypress videos
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: ignore  # Se não encontrar arquivos, ignora

